#数据库源
spring:
  jackson:
    generator:
      write_numbers_as_strings: true #强制数字以字符串输出
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://blackjun.cn:3306/black_yun?useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/black_yun?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: pjh132
#    password: PJH_132pjh
#mybatis-plus日志
mybatis-plus:
  type-aliases-package: com.black.*.pojo
  mapper-locations : classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#端口号
server:
  # 解决静态资源中文乱码问题！
  servlet:
    encoding:
      force: true
  port: 8088

